[parity]
chain = "./genesis.json"
base_path = "./data"

[account]
password = ["password"]
unlock = ["0xbfe06b543964758e1e79033798e684371b7f9996"]

[ui]
force = true
disable = false

[network]

[rpc]
port = 8545
apis = ["web3", "eth", "net", "parity", "parity_accounts", "personal", "traces", "rpc", "secretstore"]
hosts = ["all"]

[websockets]

[ipc]

[dapps]

[secretstore]

[ipfs]

[mining]
engine_signer = "0xbfe06b543964758e1e79033798e684371b7f9996"
force_sealing = false

[footprint]

[snapshots]

[vm]

[misc]
